import type { Metadata } from 'next';
import { Unbounded } from 'next/font/google';
import { fontHeading } from '@/lib/fonts';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';
import dynamic from 'next/dynamic';
import { NodeSocketProvider, WalletProvider } from '@/context';

const unbounded = Unbounded({
  style: 'normal',
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-unbounded'
});

const SubstrateContextProvider = dynamic(() => import('@/context/polkadot-contex'), {
  ssr: false
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          unbounded.variable,
          fontHeading.variable
        )}
      >
        <NodeSocketProvider>
          <WalletProvider>
            <SubstrateContextProvider>{children}</SubstrateContextProvider>
          </WalletProvider>
        </NodeSocketProvider>
        <Toaster />
      </body>
    </html>
  );
}
